extract error message from response body
Azure-Samples/power-bi-embedded-integrate-report-into-web-app pull request #46
Opened 2017-01-18 14:47 UTC by MahirDiab

2017-01-18 15:03 UTC, ali-hamud requested changes

2017-01-18 15:03 UTC, ali-hamud commented on ProvisionSample/Program.cs
> +                Console.WriteLine("Ooops, something broke: {0}", ex.Message);
Error message:

2017-01-18 15:03 UTC, ali-hamud commented on ProvisionSample/Program.cs
> +                    if (error.Error.Details != null && error.Error.Details.FirstOrDefault() != null)
error.Error.Details.FirstOrDefault() is called twice.
save it in paramter inside the if and check its value.

2017-01-18 15:03 UTC, ali-hamud commented on ProvisionSample/Program.cs
> +                    else if (error.Error.Code != null)
in place of error.Error.Code != null
you should write:
!string.IsNullOrEmpty(error.Error.Code)

2017-01-18 15:03 UTC, ali-hamud commented on ProvisionSample/Program.cs
> +                    else if (error.Error.Code != null)
no need for else if.
if both exist, print both.

2017-01-18 15:03 UTC, ali-hamud commented on ProvisionSample/Program.cs
> +                ex.Response.Headers.TryGetValue("RequestId", out requestIds);
seems like TryGetValue returns boolean.
check its value in addition for the check requestIds != null

2017-01-18 15:03 UTC, ali-hamud commented on ProvisionSample/Program.cs
> +                    Console.WriteLine("RequestId : {0}", requestIds.FirstOrDefault());
you can do here (and it's better):
if (requestIds.Any()) { requestIds.First() }
without or default (since Any will return true if it's not empty.

2017-01-22 08:47 UTC, eligr approved these changes

2017-01-22 11:22 UTC, ali-hamud approved these changes

2017-01-22 11:33 UTC, merged